Bus_reservation/src/Bus_reservation/urls.py
from django.urls import re_path,include
from django.contrib import admin

urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^', include('bus.urls')),
    re_path(r'^', include('bookTicket.urls')),
    re_path(r'^', include('account.urls')),
    re_path(r'^account/', include('django.contrib.auth.urls')),
]

Bus_reservation/src/account/urls.py
from django.urls import re_path
from django.contrib.auth import views as auth_views
from . import views
app_name = 'account'
urlpatterns = [
    re_path(r'^register/$',views.register,name='register'),
    re_path(r'^my_account/$',views.my_account,name= 'my_account'),
    re_path(r'^ticket-details/(?P<ticket_id>[−\w]+)/$', views.ticket_details,name='ticket_details'),
    re_path(r'^accounts/login/$', auth_views.LoginView.as_view() ,{'template_name': 'registration/login.html' }, name='login'),
]

Bus_reservation/src/bus/urls.py
from django.urls import re_path
from . import views
app_name = 'bus'
urlpatterns  = [
    re_path(r'^$',views.index,name='index'),
#     url (r'^category/(?P<category_slug>[−\w]+)/$',views.show_category, name='catalog_category'),
    re_path(r'^search-bus/$', views.search_bus,name='searchBus'),
    re_path(r'^autocomplete_pick/$', views.autocomplete_pick,name='pickareas'),
    re_path(r'^autocomplete_drop/$', views.autocomplete_drop,name='dropareas'),
]

Bus_reservation/src/templates/tags/footer.html
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <ul class="list-inline">
                        <li>
                            <a href="{% url 'bus:index'%}">Home</a>
                        </li>
                        <li class="footer-menu-divider">&sdot;</li>
                        <li>
                            <a href="#about">About</a>
                        </li>
                        
          
                        <li class="footer-menu-divider">&sdot;</li>
                        <li>
                            <a href="#contact">Contact</a>
                        </li>
                    </ul>
                    <p class="copyright text-muted small">Copyright &copy; Bus reservation system 2016. All Rights Reserved</p>
                </div>
            </div>
        </div>
    </footer>

Bus_reservation/src/templates/tags/navigation.html
{% load static%}

<nav class="navbar navbar-default navbar-fixed-top topnav" role="navigation">
        <div class="container topnav">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
               
	 <a class="navbar-brand topnav" href="{% url 'bus:index'%}"> <img src="{%static 'images/homepage/icon4.jpg'%}"></a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="#about">About</a>
                    </li>
                    <li>
                        <a href="#contact">Contact</a>
                    </li>
                    
                    
			        {% if user.is_authenticated %}
			         <li>
				        <a href="{% url 'account:my_account' %}">My Account</a>
				    </li>
			        <li>
			            <a href="{% url 'logout' %}">Logout</a>
			           </li>
			        {% else %}
			       
				    <li>
			            <a href="{% url 'account:register' %}">Sign Up</a>
			            </li>
			            <li>
			            <a href="{% url 'login' %}">Login</a>
			            </li>
			        {% endif %}
     				
     				
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>