Bus_reservation/src/Bus_reservation/urls.py
from django.urls import re_path,include
from django.contrib import admin

urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^', include('bus.urls')),
    re_path(r'^', include('bookTicket.urls')),
    re_path(r'^', include('account.urls')),
    re_path(r'^account/', include('django.contrib.auth.urls')),
]

Bus_reservation/src/bookTicket/urls.py
from django.urls import re_path
from . import views
app_name = 'bookTicket'
urlpatterns  = [
    re_path(r'^book-ticket/(?P<bus_id>[−\w]+)/$', views.book_ticket,name='bookTicket'),
]

Bus_reservation/src/bus/urls.py
from django.urls import re_path
from . import views
app_name = 'bus'
urlpatterns  = [
    re_path(r'^$',views.index,name='index'),
#     url (r'^category/(?P<category_slug>[−\w]+)/$',views.show_category, name='catalog_category'),
    re_path(r'^search-bus/$', views.search_bus,name='searchBus'),
    re_path(r'^autocomplete_pick/$', views.autocomplete_pick,name='pickareas'),
    re_path(r'^autocomplete_drop/$', views.autocomplete_drop,name='dropareas'),
]

Bus_reservation/src/bookTicket/models.py
from django.db import models
from django.contrib.auth.models import User
from bus.models import BusInfo
# Create your models here.
class bookAticket(models.Model):
    #each indivitual status 
    PENDING = 'P'
    CONFIRMED = 'C'
    
    TICKET_STATUSES = ((PENDING,'Pending'),
                      (CONFIRMED,'Confrimed'),)
    
    #booking Info
    booking_date = models.DateTimeField()
    status = models.CharField(choices=TICKET_STATUSES,default=PENDING,max_length=2)
    ip_address = models.GenericIPAddressField()
    last_updated = models.DateTimeField(auto_now=True)
    user= models.ForeignKey(User, on_delete=models.CASCADE)
    bus = models.ForeignKey(BusInfo, on_delete=models.CASCADE)
    date=models.DateTimeField(auto_now_add=True)
    #contact Info 
    email=models.EmailField(max_length=50)
    phone = models.CharField(max_length=20)
    
    #no. of ppl
    booking_seats_num =models.IntegerField(default=1)
    fare = models.DecimalField(max_digits=9,decimal_places=2)
    
    class Meta:
        verbose_name_plural = 'Booked Tickets'
    def __str__(self):
        return 'BUSBK#00'+str(self.id)
    
    @property
    def total(self):
        total = self.fare*self.booking_seats_num
        return total
    

Bus_reservation/src/bus/models.py
from django.db import models
# Create your models here.
class BusPickArea(models.Model):
    area_name = models.CharField(max_length=50)
    slug = models.SlugField(max_length=255,unique=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        db_table='busrv_busPickArea'
        ordering=['-created_at']
    def __str__(self):
        return self.area_name
    
class BusDropArea(models.Model):
    area_name = models.CharField(max_length=50)
    slug = models.SlugField(max_length=255,unique=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        db_table='busrv_busDropArea'
        ordering=['-created_at']
    def __str__(self):
        return self.area_name
    

class BusInfo(models.Model):
    #Bus type 
    AC = 'AC'
    NON_AC = 'NAC'
    
    BUS_TYPES = ((AC,'AC Bus'),
                      (NON_AC,'Non AC bus'),)
    
    bus_name = models.CharField(max_length=50)
    slug = models.SlugField(max_length=255,unique=True)
    bus_description = models.TextField()
    type = models.CharField(choices=BUS_TYPES,default=AC,max_length=10)
    arriving_time= models.TimeField()
    depature_time= models.TimeField()
    arriving_from = models.ForeignKey(BusPickArea,unique=False,on_delete=models.CASCADE)
    depature_at = models.ForeignKey(BusDropArea,unique=False,on_delete=models.CASCADE)
    fare = models.DecimalField(max_digits=9,decimal_places=2)
    no_of_seats = models.IntegerField(default=10)
    is_active = models.BooleanField(default=True)    
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image = models.ImageField(upload_to='images/bus/main/')
    class Meta:
        db_table='busrv_busInfo'
        ordering=['-created_at']
    def __str__(self):
        return self.bus_name

Bus_reservation/src/bookTicket/views.py
from django.shortcuts import render,get_object_or_404
from django.template import RequestContext
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.urls import reverse
from bus.models import BusInfo
from .models import bookAticket

# Create your views here.
@login_required
def book_ticket(request,bus_id,template_name='bus/book_ticket_form.html'):
    page_title = 'Book a ticket'
    bus_info = get_object_or_404(BusInfo,id=bus_id)
    #get all post data in postdata variable
    postdata=request.POST.copy()
    if request.method == 'POST':
        if postdata['bookticket'] == 'Book Ticket':
            #create a object for save
            bookTicket = bookAticket()
            bookTicket.email=postdata.get('email',0)
            bookTicket.phone = postdata.get('phone',0)
            bookTicket.booking_seats_num = postdata.get('noofseats',0)
            bookTicket.fare = postdata.get('fare_bus',0)
            if(request.user.is_authenticated):
                bookTicket.user = request.user
            bookTicket.booking_date = postdata.get('book_date',0)
            bookTicket.bus_id = bus_id
            bookTicket.ip_address = request.META.get('REMOTE_ADDR')
            #save details in the table
            bookTicket.save()
            receipt_url = reverse('account:my_account')
            return HttpResponseRedirect(receipt_url) 

    return render(request,template_name, locals())
    

Bus_reservation/src/bus/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import RequestContext
from .models import BusInfo,BusDropArea,BusPickArea

import json
# Create your views here.

def is_ajax(request):
    return request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest'

def index (request, template_name ='bus_resrv_system.html'):
    page_title = 'Bus'
    return render(request,template_name, locals())

def search_bus(request,template_name ='bus/search_bus.html'):
    page_title = 'Book a ticket'
    
    if request.method == 'POST':
        post_data = request.POST.copy()
        area_from_id = post_data.get('area_from_id')
        area_to_id = post_data.get('area_to_id') 
        bus_info_list= BusInfo.objects.filter(arriving_from_id=area_from_id,depature_at_id=area_to_id)
    return render(request,template_name, locals())


def autocomplete_pick(request):
    if is_ajax(request):
        q = request.GET.get('term', '')
        drugs = BusPickArea.objects.filter(area_name__icontains = q )[:20]
        results = []
        for drug in drugs:
            drug_json = {}
            drug_json['id'] = drug.id
            drug_json['label'] = drug.area_name
            drug_json['value'] = drug.area_name
            results.append(drug_json)
        data = json.dumps(results) 
    else:
        data = 'fail'
    mimetype = 'application/json'
    return HttpResponse(data, mimetype)

def autocomplete_drop(request):
    if is_ajax(request):
        q = request.GET.get('term', '')
        drugs = BusDropArea.objects.filter(area_name__icontains = q )[:20]
        results = []
        for drug in drugs:
            drug_json = {}
            drug_json['id'] = drug.id
            drug_json['label'] = drug.area_name
            drug_json['value'] = drug.area_name
            results.append(drug_json)
        data = json.dumps(results) 
    else:
        data = 'fail'
    mimetype = 'application/json'
    return HttpResponse(data, mimetype)

Bus_reservation/src/templates/bus/book_ticket_form.html
{% extends "bus_resrv_system.html" %}
{% load static %}
{% block content %}
<div class="intro-header">
        <div class="container">
		
            <div class="row">
                <div class="col-lg-12">
                  <div class="intro-message ">
                   	<div class=" OpacblackLayer">
                        <h2>{{bus_info.bus_name}}</h2>
                        <h3>Book a ticket</h3>
                        <hr class="intro-divider">
                        <div class="row">
						  <div class="col-xs-6">
						  <table class="table table-bordered" >
						  <tr>
							  <td>
							   <img src="{% static ''%}{{bus_info.image}}" width=360 />
							  </td>
						  </tr>
						  <tr bgcolor="#FFFFFF" style="color:black">	
							  <td>
							  Fare : &nbsp; Rs {{bus_info.fare|floatformat}}/Per person
							  </td>
						  </tr>
						  <tr bgcolor="#FFFFFF" style="color:black">
							  <td>
							   Depart:&nbsp; &nbsp;&nbsp;{{bus_info.depature_time}}<br/>
								Arrive :&nbsp;&nbsp;&nbsp;{{bus_info.arriving_time}} 
							  </td>
						  </tr>
						  <tr bgcolor="#FFFFFF" style="color:black">
							  <td>
							  Type:&nbsp;&nbsp; {{bus_info.type}}
							  </td>
						  </tr>
						  <tr bgcolor="#FFFFFF" style="color:black">
							  <td>
							   {{bus_info.bus_description|slice:":150"}}
							  </td>
						  </tr>
						  
						  </table>
						</div>
						  <div class="col-xs-6">
						  <form method='POST'action=".">
								{% csrf_token %}
								
								 <div class="row">
									<div class="form-group col-xs-9">
								     	 <label for="email">Email:</label>
								      	 <input type="email" name="email" placeholder="Please enter your email" id="email"  class="form-control input-sm " required/>
								      	
								      	 
								    </div>
								 </div>
								 <div class="row">
								    <div class="form-group col-xs-9">
								      	<label for="phone">Phone no.:</label>
								     	<input type="text" name="phone" pattern="[7-9]{1}[0-9]{9}" placeholder="Please enter your phone no." id="phone"  class="form-control input-sm" required/>
								     	
								    </div>
								  </div>
								  <div class="row">
								    <div class="form-group col-xs-9">
								      	<label for="bookDate">Booking Date</label>
        								<input class="min-today form-control input-sm" id="min" type="date" name="book_date" placeholder="YYYY-MM-DD" data-date-split-input="true" required/>								     	
								    </div>
								  </div>
								  <div class="row">
									<div class="form-group col-xs-9">
								     	 <label for="noofseats">No of seats:</label>
								      	 <input type="number" min="1" max="{{bus_info.no_of_seats}}" name="noofseats" placeholder="Please enter no of seats" id="noofseats"  class="form-control input-sm " required/>
								      	 <input type="hidden" name="fare_bus" value="{{bus_info.fare}}"/>
								    </div>
								 </div>
								  <div class="row">
									<div class="form-group col-xs-9">
										<input type="submit" name="bookticket" value="Book Ticket"  class="btn btn-primary" />
									 </div>
								</div>
								</form>
								<div class="row">
									<div class=" col-xs-9">
										 <table class="table table-bordered" >
										  <tr>
											  <td>
											   Terms & Conditions*
											  <p>1. Bus Reservation System* is an online marketplace. It does not operate bus services of its own. In order to provide a comprehensive choice of bus operators, departure times and prices to customers, it has tied up with many bus operators.</p>											
											  <p>2. Issuing a valid ticket</p>
											  <p>3. Seat numbers wil be given at the time of boarding the bus</p>
										  
											  </td>
										  </tr>
										 </table>
									 </div>
								</div>
								 </div>
						  
						  </div>
						  
						  
						</div>
                    
                    </div>
                </div>
            </div>
		
        </div>
        <!-- /.container -->

    </div>
    <!-- /.intro-header -->
    <script>
    $(function(){
    $('[type="date"].min-today').prop('min', function(){
        return new Date().toJSON().split('T')[0];
    });
});
    </script>
    
  {% endblock %}

Bus_reservation/src/templates/bus/search_bus.html
{% extends "bus_resrv_system.html" %}
{% load static %}
{% block content %}
 <div class="intro-search">
        <div class="container">
		
            <div class="row">
                <div class="col-lg-12">
                    <div class="intro-message">
							 <h2 class="OpacblackLayer">Online Bus Tickets Booking</h2>
						 	 <h3 > Search buses </h3>
						 	 <hr class="intro-divider">
						 	 <div class="md-5 col-md-offset-2 column " >
								<form method='POST'action="." >
								{% csrf_token %}
									<div class="form-group col-xs-5">
								     	 <label for="area_from">From:</label>
								      	 <input type="text" name="area_from" placeholder="Enter a city/area you want to depart from." id="area_from"  class="form-control input-sm "/>
								      	 <input type="hidden" name="area_from_id" id="area_from_id"  value="1"  />
								      	 
								    </div>
								    <div class="form-group col-xs-5">
								      	<label for="area_to">To:</label>
								     	<input type="text" name="area_to" placeholder="Enter a city/area you want to arrive to" id="area_to"  class="form-control input-sm"/>
								     	<input type="hidden" name="area_to_id" id="area_to_id" value="1" />
								     	
								    </div>
									<div class="form-group col-xs-10">
										<input type="submit" name="search_bus" value="Search Buses"  class="btn btn-primary" />
									 </div>
								</form>
						 	 </div>
						 <div>
						 {%if bus_info_list %}
						  <table class="table">
								   <thead>
								      <tr>
								       <td>Bus</td>
								        <td>Travels</td>
								        <td>Type</td>
								        <td>Fare</td>
								        <td>Timings</td>
								        <td>Description</td>
								        <td></td>
								      </tr>
								    </thead>
								    <tbody>
								     {%for bus_info in bus_info_list %}
								     <tr bgcolor="#FFFFFF" style="color:black">
								    	<td><a href="#" data-toggle="modal" data-target="#myModal{{bus_info.id}}"><img src="{% static ''%}{{bus_info.image}}" width=70 /></a>
								    			<!-- Modal -->
												  <div class="modal fade" id="myModal{{bus_info.id}}" role="dialog">
												    <div class="modal-dialog">
												    
												      <!-- Modal content-->
												      <div class="modal-content">
												        <div class="modal-header">
												          <button type="button" class="close" data-dismiss="modal">&times;</button>
												          <h4 class="modal-title">{{bus_info.bus_name}}</h4>
												        </div>
												        <div class="modal-body">
												          <p><img src="{% static ''%}{{bus_info.image}}"  width=400 /></p>
												        </div>
												        <div class="modal-footer">
												          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
												        </div>
												      </div>  
												    </div>
												  </div>								    	
								    	</td>
								        <td> {{bus_info.bus_name}}</td>
								        <td>{{bus_info.type}}</td>
								        <td>Rs {{bus_info.fare|floatformat}}/Per person</td> 
								        <td>
								       	    Depart: {{bus_info.depature_time}}<br/>
								        	Arrive : {{bus_info.arriving_time}} 
								        	
								        </td>
								        <td>{{bus_info.bus_description|slice:":60"}}...<br/>
								       			<a href="#" data-toggle="modal" data-target="#desc{{bus_info.id}}"><small>Read more</small></a>
									   				<!-- Modal description	 -->
													  <div class="modal fade" id="desc{{bus_info.id}}" role="dialog">
													    <div class="modal-dialog">
													    
													      <!-- Modal content-->
													      <div class="modal-content">
													        <div class="modal-header">
													          <button type="button" class="close" data-dismiss="modal">&times;</button>
													          <h4 class="modal-title">{{bus_info.bus_name}}</h4>
													        </div>
													        <div class="modal-body">
													          <p>{{bus_info.bus_description}}</p>
													        </div>
													        <div class="modal-footer">
													          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
													        </div>
													      </div>
													    </div>
													  </div>				
								        </td>
								         <td><a href="{% url 'bookTicket:bookTicket' bus_id=bus_info.id %}" class="btn btn-success">Book Now</a></td>
								      </tr>
									{%endfor%}
								      
								    </tbody>
								  </table> 
							
						 {%endif%}
						 </div>
        
                    </div>
                </div>
            </div>
		
        </div>
        <!-- /.container -->

    </div>
    <!-- /.intro-header -->
  
    
<script>
 $(function() {
    $( "#area_from" ).autocomplete({
      source: '{% url 'bus:pickareas' %}',
      select: function( event, ui ) {
      	$("#area_from_id").val(ui.item.id);
      }
    });
  });

 $(function() {
    $( "#area_to" ).autocomplete({
      source: '{% url 'bus:dropareas' %}',
      select: function( event, ui ) {
      	$("#area_to_id").val(ui.item.id);
      }
    });
  });

</script>  
    
{% endblock %}