Bus_reservation/src/Bus_reservation/urls.py
from django.urls import re_path,include
from django.contrib import admin

urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^', include('bus.urls')),
    re_path(r'^', include('bookTicket.urls')),
    re_path(r'^', include('account.urls')),
    re_path(r'^account/', include('django.contrib.auth.urls')),
]

Bus_reservation/src/bus/urls.py
from django.urls import re_path
from . import views
app_name = 'bus'
urlpatterns  = [
    re_path(r'^$',views.index,name='index'),
#     url (r'^category/(?P<category_slug>[−\w]+)/$',views.show_category, name='catalog_category'),
    re_path(r'^search-bus/$', views.search_bus,name='searchBus'),
    re_path(r'^autocomplete_pick/$', views.autocomplete_pick,name='pickareas'),
    re_path(r'^autocomplete_drop/$', views.autocomplete_drop,name='dropareas'),
]

Bus_reservation/src/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

	<title>{% block title %}{% if page_title %}{{ page_title }} - {% endif %} Bus Reservation System{% endblock %}</title>

    <!-- Bootstrap Core CSS -->
    <link href="{%static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{%static 'css/landing-page.css' %}" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="{%static 'font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href="{%static 'font-awesome/css/font-google.css' %}" rel="stylesheet" type="text/css">
    
 	<!-- Autocomplete css-->
 	 <link rel="stylesheet" href="{%static 'css/jquery-ui.css' %}">
 	   
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
   
    <![endif]-->
    
       <!-- jQuery -->
   	   <script src="{%static 'js/jquery.js' %}"></script>
   	   
   	   <!-- Autocomplete Js-->
       <!-- <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
  	   <script src="//code.jquery.com/jquery-1.10.2.js"></script>
 	   <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>-->
 	   
  	   <script src="{%static 'js/jquery-1.10.2.js' %}"></script>
 	   <script src="{%static 'js/jquery-ui.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{%static 'js/bootstrap.min.js' %}"></script>

</head>
<body>
     {% block site_wrapper %}{% endblock %}
</body>
</html>

Bus_reservation/src/templates/bus_resrv_system.html
{% extends "base.html" %}

{% load static %}
{% block site_wrapper %}
 <!-- Navigation -->
 {% include 'tags/navigation.html' %}
 <!--end navigation-->
 
    <!-- Container -->
     {% block content %}
    <div class="intro-header">
        <div class="container">
		
            <div class="row">
                <div class="col-lg-12">
                    <div class="intro-message">
                   
                        <h1>Bus Reservation System</h1>
                        <h3>Where the journey begins!!!</h3>
                        <hr class="intro-divider">
                        <ul class="list-inline intro-social-buttons">
                            <li>
                                <a href="{% url 'bus:searchBus' %}" class="btn btn-default btn-lg"><i class="fa fa-bus fa-fw"></i> <span class="network-name">Book a ticket</span></a>
                            </li>

                        </ul>
                    
                    </div>
                </div>
            </div>
		
        </div>
        <!-- /.container -->

    </div>
    <!-- /.intro-header -->
 {% endblock %}
    <!-- Page Content -->

	<a name="about"></a>
    <div class="content-section-a">

        <div class="container">
            <div class="row">
                <div class="col-lg-5 col-sm-6">
                    <hr class="section-heading-spacer">
                    <div class="clearfix"></div>
                    <h2 class="section-heading">Online ticket booking system:<br>No 'Line' on Online</h2>
                    <p class="lead">Bus Reservation System is designed to automate the online ticket purchasing through an easy online bus booking system.With the bus ticket reservation system you can manage reservations, clients data and passengers lists.</p>
                </div>
                <div class="col-lg-5 col-lg-offset-2 col-sm-6">
                    <img class="img-responsive" src="{% static 'images/booking_page/abtus2.jpg' %}" alt="">
                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>
    <!-- /.content-section-a -->

    <div class="content-section-b">

        <div class="container">

            <div class="row">
                <div class="col-lg-5 col-lg-offset-1 col-sm-push-6  col-sm-6">
                    <hr class="section-heading-spacer">
                    <div class="clearfix"></div>
                    <h2 class="section-heading">It's Simple!!!<br><small>Search for buses-Book your ticket-Board your bus</small> </h2>
                    <p class="lead">Making your life easier with bus fare comparisions,searching buses and making your journey the safe and sound.</p>
                </div>
                <div class="col-lg-5 col-sm-pull-6  col-sm-6">
                    <img class="img-responsive" width="80%" hieght="40%" src="{% static 'images/booking_page/abtus.png' %}" alt="">
                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>
    <!-- /.content-section-b -->

    <div class="content-section-a">

        <div class="container">

            <div class="row">
                <div class="col-lg-5 col-sm-6">
                    <hr class="section-heading-spacer">
                    <div class="clearfix"></div>
                    <h2 class="section-heading">Contact us :</h2>
                    <p class="lead">
                   		 <strong>Phone Contacts :</strong><br/>
							Mumbai : +91-022-345-345<br/>
							Pune : +91-022-345-346<br/>
                    		<strong>E-mail Contacts :</strong><br/>
							E-mail : support [AT] busreservation.in
					</p>
                </div>
                <div class="col-lg-5 col-lg-offset-2 col-sm-6">
                    <img class="img-responsive" src="{% static 'images/booking_page/contus.JPG' %}" alt="">
                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>
    <!-- /.content-section-a -->

	<a  name="contact"></a>
    <div class="banner">

        <div class="container">

            <div class="row">
                <div class="col-lg-6">
                    <h2>Connect to Bus Reservation:</h2>
                </div>
                <div class="col-lg-6">
                    <ul class="list-inline banner-social-buttons">
                        <li>
                            <a href="#" class="btn btn-default btn-lg"><i class="fa fa-twitter fa-fw"></i> <span class="network-name">Twitter</span></a>
                        </li>
                        <li>
                            <a href="#" class="btn btn-default btn-lg"><i class="fa fa-facebook fa-fw"></i> <span class="network-name">Facebook</span></a>
                        </li>
                        <li>
                            <a href="#" class="btn btn-default btn-lg"><i class="fa fa-linkedin fa-fw"></i> <span class="network-name">Linkedin</span></a>
                        </li>
                    </ul>
                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>
    <!-- /.banner -->

    <!-- Footer -->
    {%include 'tags/footer.html' %}
	<!-- End of footer -->

{% endblock %}